spring:
  application:
    name: mentorbook-backend

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=MentorBookingDB;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      hibernate.default_schema: dbo

  web:
    resources:
      add-mappings: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth2_client_id}
            client-secret: ${oauth2_client_secret}
            redirect-uri: http://localhost:8080/oauth2/callback
    resourceserver:
      jwt:
        issuer-uri: https://your-issuer-uri

security:
  csrf:
    enabled: false

ImageController:
  saveLocation: C:\Users\daeor\Documents\Project\Image\